app/models.py
from flask_login import UserMixin
from . import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_socketio import SocketIO

# init SQLAlchemy so we can use it later in our models
db = SQLAlchemy()

def create_app():
	app = Flask(__name__)

	app.config['SECRET_KEY'] = 'secret-key-goes-here'
	app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
	app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

	db.init_app(app)
	
	login_manager = LoginManager()
	login_manager.login_view = 'auth.login'
	login_manager.init_app(app)

	from .models import User

	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(int(user_id))

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint)


	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)
	
	from .pain import pain

	app.register_blueprint(pain)

	return app

app/app.py
from flask import Flask
from flask_socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO(app, logger=True, engineio_logger=True)

from .pain import *

app.register_blueprint(pain, url_prefix='/pain')

if __name__ == '__main__':
    socketio.run(app)

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user
from .models import User
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login1.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


@auth.route('/signup')
def signup():
    return render_template('signup1.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/main.py
import os

from flask import Blueprint, render_template, request, jsonify, Response
from flask_login import login_required, current_user
from camera import Camera
from . import db
import json

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)

@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html', name=current_user.name)

@main.route('/classroom')
@login_required
def classroom():
    return render_template('classroom.html', name=current_user.name)

@main.route('/courses')
@login_required
def courses():
    return render_template('courses.html', name=current_user.name)

@main.route('/past_papers')
@login_required
def past_papers():
    return render_template('file-dir.html', name=current_user.name)

@main.route('/projects')
@login_required
def projects():
    return render_template('projects.html', name=current_user.name)

@main.route('/mentor') #WIP
@login_required
def mentor():
    return render_template('mentor.html', name=current_user.name)

from time import time

class Camera(object):
    def __init__(self):
        self.frames = [open(f + '.jpg', 'rb').read() for f in ['1', '2', '3']]

    def get_frame(self):
        return self.frames[int(time()) % 3]

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@main.route('/video_feed')
def video_feed():
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

# @main.route('/ide') #WIP
# @login_required
# def ide():
#     return render_template('profile.html', name=current_user.name)

app/pain/__init__.py
from flask import Blueprint

pain = Blueprint('pain', __name__)

from . import views

app/pain/views.py
from flask import Blueprint, render_template, request, jsonify
from flask_socketio import SocketIO, emit, join_room, leave_room
from . import pain
from ..app import socketio
import jsonify

# Channel Data Global Variables
channel_list = {"general": [] }
present_channel = {"initial":"general"}

@pain.route("/pain", methods=["POST", "GET"])
def index(methods=['GET', 'POST']):
    if request.method == "GET":
        # Pass channel list to, and use jinja to display already created channels
        return render_template("vindex.html", channel_list=channel_list)

    elif request.method == "POST":
        channel = request.form.get("channel_name")
        user = request.form.get("username")

        # Adding a new channel
        if channel and (channel not in channel_list):
            channel_list[channel] = []
            return jsonify({"success": True})
        # Switching to a different channel
        elif channel in channel_list:
            # send channel specific data to client i.e. messages, who sent them, and when they were sent
            # send via JSON response and then render with JS
            print(f"Switch to {channel}")
            present_channel[user] = channel
            channel_data = channel_list[present_channel[user]]
            return jsonify(channel_data)
        else:
            return jsonify({"success": False})

@socketio.on("create channel")
def create_channel(new_channel):
    emit("new channel", new_channel, broadcast=True)

@socketio.on("send message")
def send_message(message_data):
    channel = message_data["current_channel"]
    channel_message_count = len(channel_list[channel])
    del message_data["current_channel"]
    channel_list[channel].append(message_data)
    message_data["deleted_message"] = False
    if(channel_message_count >= 100):
        del channel_list[channel][0]
        message_data["deleted_message"] = True
    emit("recieve message", message_data, broadcast=True, room=channel)

@socketio.on("delete channel")
def delete_channel(message_data):
    channel = message_data["current_channel"]
    user = message_data["user"]
    present_channel[user] = "general"
    del message_data["current_channel"]
    del channel_list[channel]
    channel_list["general"].append(message_data)
    message_data = {"data": channel_list["general"], "deleted_channel": channel}
    emit("announce channel deletion", message_data, broadcast=True)

@socketio.on("leave")
def on_leave(room_to_leave):
    print("leaving room")
    leave_room(room_to_leave)
    emit("leave channel ack", room=room_to_leave)

@socketio.on("join")
def on_join(room_to_join):
    print("joining room")
    join_room(room_to_join)
    emit("join channel ack", room=room_to_join)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
	<style type="text/css">
		#background {
			background: linear-gradient(to bottom right,#fec811, #e73600, #b400cf); 
			background-size: 2000% 100%;
			animation: gradient 4s linear infinite;
			animation-direction: alternate;
		}
		@keyframes gradient {
			0% {background-position: 0%}
			100% {background-position: 100%}
		}		
	</style>
    {% block head %}
    {% endblock head %}
</head>

<body>
    <section id="background" class="hero is-dark is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
							<a href="{{ url_for('main.index') }}" class="navbar-item">
								Home
							</a>
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.profile') }}" class="navbar-item">
								Profile
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.dashboard') }}" class="navbar-item">
								Dashboard
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.classroom') }}" class="navbar-item">
								Classroom
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.courses') }}" class="navbar-item">
								Courses
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.past_papers') }}" class="navbar-item">
								Papers
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.projects') }}" class="navbar-item">
								Projects
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('main.mentor') }}" class="navbar-item">
								Mentor
							</a>
							{% endif %}
							{% if not current_user.is_authenticated %}
							<a href="{{ url_for('auth.login') }}" class="navbar-item">
								Login
							</a>
							<a href="{{ url_for('auth.signup') }}" class="navbar-item">
								Sign Up
							</a>
							{% endif %}
							{% if current_user.is_authenticated %}
							<a href="{{ url_for('auth.logout') }}" class="navbar-item">
								Logout
							</a>
							{% endif %}
						</div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock content %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/del.html
<body>
    <div class="login-header">
        <h1>WEBSITE NAME</h1>
    </div>
    <br>
    
    <div>
        <div class="content-section desktopView" style="margin-left: 300px; margin-right: 300px;">
            <form method="POST">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log in to your account</legend>
                    
                    <div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
                        Username<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput form-control" required id="id_username"> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class=" requiredField">
                        Password<span class="asteriskField">*</span> </label> <div class=""> <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required id="id_password"> </div> </div>

                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                </div>
            </form>
            </div>
        </div>
        


        <div>

    
            <h1>University Careers</h1>
            <div class="tbl-header">
              <table cellspacing="0" cellpadding="0" border="0">
              <thead>
                  <tr>
                  <th>Careers</th>
                  <th>Universities</th>
                  </tr>
              </thead>
              </table>
          </div>
          <div class="tbl-content">
              <table cellspacing="0" cellpadding="0" border="0">
              <tbody>
                  <tr>
                  <td>Medicine</td>
                  <td>Oxford</td>
                  </tr>
                  <tr>
                  <td>Physiotherapy</td>
                  <td>Imperial College London</td>
                  </tr>
                  <tr>
                  <td>Bioengineering</td>
                  <td>Cambridge</td>
                  </tr>
                  <tr>
                  <td>Mathematics</td>
                  <td>Yale</td>
                  </tr>
                  <tr>
                  <td>Astronomy</td>
                  <td>Harvard</td>
                  </tr>
                  <tr>
                  <td>Computer Science</td>
                  <td>National University of Singapore</td>
                  </tr>
              </tbody>
              </table>
      
      
      
      
          </div>
      
      
      
        </div>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<img style="filter: brightness(150%); opacity: 1.0; object-fit: none; object-position: 75px 0;" src="https://cdn.discordapp.com/attachments/783630345189982231/916663663077781504/output-onlinepngtools.png">
<h2 class="subtitle">
  Equal Education for all
</h2>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>H-Chat</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Carter+One|PT+Sans+Caption|Josefin+Sans" rel="stylesheet">
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script>
        <script id="load-channel-title" type="text/template">
            <h1 id="channel-title">{% raw -%}{{channel_to_display}}{%- endraw %}</h1>
        </script>
        <script id="load-messages" type="text/template">
            <li class="media comment-item">
                <div class="media-body comment-media">
                    <h5 class="mt-0 mb-1 comment-user">{% raw -%}{{comment.user}} &middot{%- endraw %}</h5>
                    <div id="time" class="comment-time">{% raw -%}{{comment.timestamp}}{%- endraw %}</div>
                    <div class="comment-comment">{% raw -%}{{comment.message_content}}{%- endraw %}</div>
                </div>
            </li>
        </script>
        <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/styles.css', version='306') }}">
    </head>

    {% block heading %}{% endblock %}

    {% block body %}

    {% endblock %}

</html>

app/templates/login1.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="templates/main.css">
	<style type="text/css">
		.login-header {
			padding: 50px;
			text-align: center;
			background:hsl(177, 79%, 54%);
			background-image: linear-gradient(to bottom right, 
			#fec811, #e73600, #b400cf);
			color:white;
		}
		/*
		_____________________
		|    login       |
		------------------
		*/
		img{
			width: 100%;
		}
		.login_box {
			width: 1050px;
			height: 600px;
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%,-50%);
			background: #fff;
			border-radius: 10px;
			box-shadow: 1px 4px 22px -8px #0004;
			display: flex;
			overflow: hidden;
		}
		.login_box .left{
		  width: 41%;
		  height: 100%;
		  padding: 25px 25px;
		  
		}
		.login_box .right{
		  width: 59%;
		  height: 100%  
		}
		.left .top_link a {
			color: #452A5A;
			font-weight: 400;
		}
		.left .top_link{
		  height: 20px
		}
		.left .contact{
			display: flex;
			align-items: center;
			justify-content: center;
			align-self: center;
			height: 100%;
			width: 73%;
			margin: auto;
		}
		.left h3{
		  text-align: center;
		  margin-bottom: 40px;
		}
		.left input {
			border: none;
			width: 80%;
			margin: 15px 0px;
			border-bottom: 1px solid #4f30677d;
			padding: 7px 9px;
			width: 100%;
			overflow: hidden;
			background: transparent;
			font-weight: 600;
			font-size: 14px;
		}
		.left{
			background: linear-gradient(-45deg, #dcd7e0, #fff);
		}
		.submit {
			border: none;
			padding: 15px 70px;
			border-radius: 8px;
			display: block;
			margin: auto;
			margin-top: 120px;
			background: #583672;
			color: #fff;
			font-weight: bold;
			-webkit-box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
			-moz-box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
			box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
		}
		.right {
			background: linear-gradient(212.38deg, rgba(242, 57, 127, 0.7) 0%, rgba(175, 70, 189, 0.71) 100%),url(https://static.seattletimes.com/wp-content/uploads/2019/01/web-typing-ergonomics-1020x680.jpg);
			color: #fff;
			position: relative;
		}
		
		.right .right-text{
		  height: 100%;
		  position: relative;
		  transform: translate(0%, 45%);
		}
		.right-text h2{
		  display: block;
		  width: 100%;
		  text-align: center;
		  font-size: 50px;
		  font-weight: 500;
		}
		.right-text h5{
		  display: block;
		  width: 100%;
		  text-align: center;
		  font-size: 19px;
		  font-weight: 400;
		}
		
		.right .right-inductor{
		  position: absolute;
		  width: 70px;
		  height: 7px;
		  background: #fff0;
		  left: 50%;
		  bottom: 70px;
		  transform: translate(-50%, 0%);
		}
		.top_link img {
			width: 28px;
			padding-right: 7px;
			margin-top: -3px;
		}
	</style>
{% endblock head %}


{% block content %}

<section class="login">
    <div class="login_box">
        <div class="left">
            <div style="color: #452A5A; text-align: left" class="top_link"><a href="/"><img src="https://drive.google.com/u/0/uc?id=16U__U5dJdaTfNGobB_OpwAJ73vM50rPV&export=download" alt="">Return home</a></div>
            <div class="contact">


                <form method="POST" action="/login">
                    <h3 style="color: #452A5A;">Login</h3>
					{% with messages = get_flashed_messages() %}
					{% if messages and messages != "Please log in to access this page."%}
						<div class="notification is-danger">
							{{ messages[0] }}
						</div>
					{% endif %}
					{% endwith %}
                    <div class="field">
                        <div class="control">
                            <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                        </div>
                    </div>


                    <div class="field">
                        <div class="control">
                            <input class="input is-large" type="password" name="password" placeholder="Your Password">
                        </div>
                    </div>

                    <button class="submit">LET'S GO</button>
                </form>


            </div>
        </div>
        <div class="right">
            <div class="right-text">
                <h2>Liber</h2>
                <h5>Everyone deserves an Equal Opportunity to Learn</h5>
            </div>
        </div>
    </div>
</section>

{% endblock content%}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
	<h3 class="title">Sign Up</h3>
	<div class="box">
		{% with messages = get_flashed_messages() %}
		{% if messages %}
			<div class="notification is-danger">
				{{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
			</div>
		{% endif %}
		{% endwith %}
		<form method="POST" action="/signup">
			<div class="field">
				<div class="control">
					<input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
				</div>
			</div>

			<div class="field">
				<div class="control">
					<input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
				</div>
			</div>

			<div class="field">
				<div class="control">
					<input class="input is-large" type="password" name="password" placeholder="Password">
				</div>
			</div>

			<button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
		</form>
	</div>
</div>
{% endblock %}

app/templates/template.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="main.css">
</head>

<body>

    <div class="language-picker js-language-picker">
        <form action="" class="language-picker__form">
          <label for="language-picker-select">Select your language</label>
      
          <select name="language-picker-select" id="language-picker-select">
            <option>Deutsch</option>
            <option>English</option>
            <option>Français</option>
            <option>Italiano</option>
            <option>普通话</option>
            <option>日本語</option>
            <option>한국어</option>
            <option>Bahasa Melayu</option>
            
            <!-- other language options -->
          </select>
        </form>
      </div>

</body>


</html>

app/templates/video.html
<html>
  <head>
    <title>Video Streaming Demonstration</title>
  </head>
  <body>
    <h1>Video Streaming Demonstration</h1>
    <img src="{{ url_for('video_feed') }}">
  </body>
</html>

app/templates/vindex.html
{% extends "layout.html" %}

{% block heading %}
{% endblock %}

{% block body %}
    <body>
        <div class="row flex-nowrap app-area">
            <div class="col-channel-width color-channel-test">
                <h4 id="user"></h4>
                <h1 id="channel-heading">Channels</h1>
                <form id="add-channel-form">
                    <div class="input-group mb-3 channel-input">
                        <input id="channel" type="text" class="form-control" placeholder="New channel name" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button id="submit-add-channel" type="submit" class="btn btn-light add-button"><div id="plus">+</div></button>
                        </div>
                    </div>
                </form>
                <ul id="channels">
                    {% for channel in channel_list %}
                        <form id="switch-channel-form">
                            <button id="submit-switch-channel" type="submit" value={{channel}}><li id="channel-option"># {{channel}}</li></button>
                        </form>
                    {% endfor %}
                </ul>
            </div>
            <div id="message-view" class="col color-message-test">
                <div class="comment-container">
                    <ul id="comment-list" class="list-unstyled">
                    </ul>
                </div>
                <form id="message-form">
                    <div class="input-group mb-3 message-input">
                        <input id="message-input" type="text" class="form-control" placeholder="Enter message here" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button id="submit-send-message" type="submit" class="btn btn-light add-button"><div id="send">Send</div></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </body>
{% endblock %}